# Generated by Django 5.2.17 on 2026-09-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdomain',
            name='domain_type',
            field=models.CharField(choices=[('SUBDOMAIN', 'Platform Subdomain'), ('CUSTOM', 'Custom Domain')], default='SUBDOMAIN', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='db_strategy',
            field=models.CharField(choices=[('SHARED_DB', 'Shared Database (tenant_id)'), ('SEPARATE_DB', 'Dedicated Database'), ('ISOLATED_SCHEMA', 'Dedicated Schema')], default='SHARED_DB', max_length=30),
        ),
    ]
