# Generated by Django 5.2.17 on 2026-09-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_customdomain_domain_type_tenant_db_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdomain',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customdomain',
            name='verification_token',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
